# Generated by Django 4.0.1 on 2022-01-18 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_diagnostic_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='htmlfield',
            field=models.TextField(blank=True, help_text='Add html', null=True),
        ),
        migrations.AlterField(
            model_name='diagnostic',
            name='text',
            field=models.TextField(blank=True, help_text='Add some text', null=True),
        ),
    ]
