# Generated by Django 4.0.1 on 2022-01-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_alter_diagnostic_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostic',
            old_name='htmlfield',
            new_name='html_field',
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='html_pay_pal',
            field=models.TextField(blank=True, help_text='Add PayPal html', null=True, verbose_name='Html PayPal'),
        ),
    ]
