# Generated by Django 4.0.1 on 2022-01-18 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_alter_diagnostic_html_pay_pal'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diagnostic',
            old_name='text',
            new_name='desc',
        ),
    ]
