# Generated by Django 4.0.1 on 2022-01-21 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_rename_text_diagnostic_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='ouroffer',
            name='text_en',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ouroffer',
            name='text_pl',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ouroffer',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ouroffer',
            name='title_pl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='text_en',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='text_pl',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='title_pl',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='description_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='description_pl',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_pl',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
