# Generated by Django 4.0.1 on 2022-01-21 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_ouroffer_text_en_ouroffer_text_pl_ouroffer_title_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ouroffer',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='ouroffer',
            name='text_pl',
        ),
        migrations.RemoveField(
            model_name='ouroffer',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='ouroffer',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='step',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='step',
            name='text_pl',
        ),
        migrations.RemoveField(
            model_name='step',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='step',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='description_pl',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='name_pl',
        ),
    ]
