# Generated by Django 4.0.1 on 2022-01-21 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_ouroffer_text_en_ouroffer_title_en_step_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='text_en',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
