# Generated by Django 4.0.1 on 2022-01-21 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0014_testimonial_text_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ouroffer',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='ouroffer',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='step',
            name='text_en',
        ),
        migrations.RemoveField(
            model_name='step',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='text_en',
        ),
    ]
