# Generated by Django 4.0.1 on 2022-01-21 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0018_ouroffer_text_en_ouroffer_title_en_step_text_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='title',
            field=models.CharField(blank=True, max_length=500, verbose_name='Page title'),
        ),
    ]
