# Generated by Django 3.0.8 on 2022-01-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0020_diagnostic_desc_en_diagnostic_title_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnostic',
            name='desc_bg',
            field=models.TextField(blank=True, help_text='Add some text', null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='diagnostic',
            name='title_bg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Page title'),
        ),
        migrations.AddField(
            model_name='ouroffer',
            name='text_bg',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='ouroffer',
            name='title_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='text_bg',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='step',
            name='title_bg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='description_bg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='name_bg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='testimonial',
            name='text_bg',
            field=models.TextField(max_length=2000, null=True),
        ),
    ]
