# Generated by Django 4.0.1 on 2022-01-30 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0021_auto_20220126_0950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='diagnostic',
            new_name='DiagnosticBulgaria',
        ),
    ]
